# Generated by Django 5.0.4 on 2024-04-14 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='')),
                ('bio', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('genre', models.CharField(default='genre', max_length=100)),
                ('release_date', models.DateTimeField()),
                ('song_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.songwriter')),
            ],
        ),
    ]
